spring.application.name: auth
#server.port=0
server.port: 6000
eureka.client.service-url.default-zone: http://localhost:8761/eureka
jwt.secret: secretkey
jwt.token.validity: 180000
spring.jackson.default-property-inclusion: NON_NULL