spring.application.name: gateway
eureka.client.service-url.default-zone: http://localhost:8761/eureka
jwt.secret: secretkey
spring.jackson.default-property-inclusion: NON_NULL

spring:
  cloud:
    gateway:
      routes:
        - id: auth Service
          uri: "lb://auth"
          predicates:
            - Path=/auth/**
          filters:
          #  - StripPrefix=1
            - JwtAuthenticationFilterFactory
        - id: sample API
          uri: "lb://sample"
          predicates:
            - Path=/sample/**
          filters:
          #  - StripPrefix=1
            - JwtAuthenticationFilterFactory
